export let items = [
  {
    _id: "ERRWEGG3W412553232",
    name: "Cheeseburger",
    ingredients: [
      "beef patty",
      "cheese",
      "lettuce",
      "tomato",
      "onion",
      "ketchup",
      "mayonnaise",
      "bun",
    ],
    category: "main",
    price: 8.99,
    isCompleted: false,
  },
  {
    _id: "ERRWEGG3W4WFWFW231",
    name: "French Fries",
    ingredients: ["potatoes", "salt", "pepper"],
    category: "condiment",
    price: 9.24,
    isCompleted: false,
  },
  {
    _id: "VERRG4563W412553232",
    name: "Soda",
    ingredients: ["carbonated water", "sugar", "flavoring"],
    category: "drink",
    price: 5.99,
    isCompleted: false,
  },
  {
    _id: "ELDKDHRUW412553232",
    name: "Caesar Salad",
    ingredients: [
      "romaine lettuce",
      "parmesan cheese",
      "croutons",
      "Caesar dressing",
    ],
    category: "main",
    price: 12.22,
    isCompleted: false,
  },
  {
    _id: "ERRWELSK3421553232",
    name: "Ketchup",
    ingredients: ["tomatoes", "vinegar", "sugar", "spices"],
    category: "condiment",
    price: 14.33,
    isCompleted: false,
  },
  {
    _id: "ERR883728212553232",
    name: "Lemonade",
    ingredients: ["lemons", "sugar", "water"],
    category: "drink",
    price: 13.44,
    isCompleted: false,
  },
];
